# Generated by Django 5.2.16 on 2026-09-09 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الفاعلية'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إدخال المادة'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الصلاحية'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الفاعلية'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إدخال المادة'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الصلاحية'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'مخزون منخفض'), ('expiry_soon', 'قرب انتهاء الصلاحية'), ('expired', 'منتهي الصلاحية'), ('system', 'نظام')], default='system', max_length=20, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت العملية'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in_purchase', 'فاتورة شراء'), ('in_receipt', 'أمر استلام'), ('out_sale', 'فاتورة بيع'), ('out_dispatch', 'أمر صرف'), ('out_expired', 'إتلاف منتهي الصلاحية'), ('transfer', 'نقل بين مستودعات')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
